//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Text;
    using System.Threading;

    public partial class AdminUser
    {
        public int ID { get; set; }
        public string NameUser { get; set; }
        [Required(ErrorMessage = "Không ???c phép ?? tr?ng")]
        public string RoleUser { get; set; }

        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")]
        [Required(ErrorMessage = "Không ???c phép ?? tr?ng")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }
        [Required(ErrorMessage = "Không ???c phép ?? tr?ng")]
        [DataType(DataType.Password)]
        [Compare("PasswordUser")]
        public string ConfirmPassword { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
