//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Text;
    using System.Threading;


    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }

        public int IDCus { get; set; }
        [Required(ErrorMessage = "Không ???c ?? tr?ng")]
        public string NameCus { get; set; }
        [Required(ErrorMessage = "Không ???c ?? tr?ng")]

        public string PhoneCus { get; set; }
        // Email có kí t? th??ng, in, s?, ph?i có @ sau @ là kí t? th??ng, in, s?, ph?i có d?u ch?m ch? th??ng, in t? 2-4 kí t? 
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng")]
        public string EmailCus { get; set; }
        //M?t kh?u ph?i có ch? th??ng, ch? in, t? 8 - 15 kí t?
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$")]
        [Required(ErrorMessage = "Không ???c ?? tr?ng")]
        [DataType(DataType.Password)]
        public string PassCus { get; set; }
        [Required(ErrorMessage = "Không ???c ?? tr?ng")]
        [DataType(DataType.Password)]
        // So sánh 2 m?t kh?u ph?i gi?ng nhau
        [Compare("PassCus")]
        public string ConfirmPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
